// **************************************************************************
// LOCALHOST
//@url = http://localhost:3000

// RENDER
@url = https://cse341-inventory-project.onrender.com/api-docs/
// **************************************************************************

// 1. GET all items
GET {{url}}/api/items

###

// 2. GET item by ID (Replace ID)
GET {{url}}/api/items/6988275f7d90236d0192b02d

###

// 3. POST create item
POST {{url}}/api/items
Content-Type: application/json

{
    "name": "digital camera",
    "quantity": 100,
    "category": "Electronics"
}

###

// 4. PUT update item (Replace ID)
PUT {{url}}/api/items/6990b6cf6d0ee706cc698e71
Content-Type: application/json

{
    "name": ""
}

###

// 5. DELETE item (Replace ID)
DELETE {{url}}/api/items/6990b5696d0ee706cc698e6e