// **************************************************************************
// LOCALHOST
@url = http://localhost:3000

// RENDER (Uncomment the line below to test live deployment)
// @url = https://<YOUR-RENDER-APP-NAME>.onrender.com
// **************************************************************************

// 1. GET all items
GET {{url}}/api/items

###

// 2. GET item by ID (Replace ID)
GET {{url}}/api/items/6988275f7d90236d0192b02d

###

// 3. POST create item
POST {{url}}/api/items
Content-Type: application/json

{
    "name": "Oatmeal",
    "quantity": 150,
    "category": "Groceries"
}

###

// 4. PUT update item (Replace ID)
PUT {{url}}/api/items/69882381adce4371528802ce
Content-Type: application/json

{
    "quantity": 20
}

###

// 5. DELETE item (Replace ID)
DELETE {{url}}/api/items/6988284f7d90236d0192b032